# Generated by Django 5.1.1 on 2025-09-20 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorRoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('invigilator', models.ForeignKey(limit_choices_to={'role': 'invigilator'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_rooms', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilators', to='app.room')),
            ],
            options={
                'verbose_name': 'Invigilator Room Assignment',
                'verbose_name_plural': 'Invigilator Room Assignments',
                'unique_together': {('invigilator', 'room')},
            },
        ),
    ]
