# Generated by Django 5.2.5 on 2025-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invigilator_exam_room_seating'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='testpassword', max_length=128),
        ),
    ]
