# Generated by Django 5.2.5 on 2025-09-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_debarred',
            field=models.BooleanField(default=False),
        ),
    ]
