# Generated by Django 5.1.1 on 2025-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_phone_number_customuser_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], null=True),
        ),
    ]
