# Generated by Django 5.2.5 on 2025-10-02 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='debarred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debarred_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
