# Generated by Django 5.2.5 on 2025-09-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_phone_number_customuser_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('invigilator', 'Invigilator'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
