# Generated by Django 5.2.5 on 2025-09-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_is_debarred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_debarred',
        ),
        migrations.AddField(
            model_name='student',
            name='is_debarred',
            field=models.BooleanField(default=False),
        ),
    ]
