# Generated by Django 5.1.1 on 2025-10-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_debarred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='department',
        ),
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.ManyToManyField(related_name='exams', to='app.department'),
        ),
    ]
