# Generated by Django 5.1.1 on 2025-08-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
