# Generated by Django 5.2.5 on 2025-09-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customuser_is_debarred_student_is_debarred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('invigilator', 'Invigilator'), ('admin', 'admin')], default='admin', max_length=20),
        ),
    ]
