# Generated by Django 5.1.1 on 2025-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
        ),
    ]
