# Generated by Django 5.1.1 on 2025-08-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bench_capacity',
            field=models.IntegerField(default=3),
        ),
    ]
