# Generated by Django 5.1.1 on 2025-08-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_examsession_remove_exam_date_remove_exam_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='app.examsession'),
        ),
    ]
